<?php
namespace Logic;
use Think\Controller;
class Commonsms extends Controller{
	public function sendSms($ordersArr,$sendtype){

             if($sendtype=="EFW007"||$sendtype=="EFA007"){		
			/*发送租客*/
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
			}
			//发送房东
			if($sendtype=="EFW008"||$sendtype=="EFA008"){
				$xiaArr['phonenumber']=$ordersArr['mobile']; 
				$xiaArr['smstype']=$sendtype;
				$xiaArr['timestamp']=time();
				$xiaArr['name']=$ordersArr['renter_name'];
				$xiaArr['money']=$ordersArr['order_pirce_cnt'];
				$xiaArr['orderid']=$ordersArr['order_id'];
				sendPhoneContent($xiaArr);
		    }

			
			//退款发送给租客
			if($sendtype=="EFW006"||$sendtype=="EFA006"){
				$yinArr['phonenumber']=$ordersArr['renter_phone'];
				$yinArr['smstype']=$sendtype;
				$yinArr['timestamp']=$ordersArr['create_time'];
				$yinArr['name']=$ordersArr['renter_name'];
				$yinArr['money']=$ordersArr['price_cnt'];
				$yinArr['orderid']=$ordersArr['id'];
				sendPhoneContent($yinArr);
		    }
		    //审核成功
		     if($sendtype=="EFW002"||$sendtype=="EFA002"){		
			 /*发送租客*/
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
			}

			//拒绝订单
		     if($sendtype=="EFW003"||$sendtype=="EFA003"){
			 /*发送租客*/
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
			}
			//短信发送
			if($sendtype=="EZA003"){
				$sendArr['phonenumber']=$ordersArr['mobile'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time']; 
				$sendArr['name']=$ordersArr['name']; 
				$sendArr['money']="0";
				$sendArr['orderid']="0";
				sendPhoneContent($sendArr);
			}
			//定金已退款--租客
			if($sendtype=="DJ004"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		    //定金已退款--租客
			if($sendtype=="DJ005"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }

		     //定金已退款--房东
			if($sendtype=="DJ005"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		    //定金已打款--租客
			if($sendtype=="DJ006"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		     //定金已打款--房东
			if($sendtype=="DJ007"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }

		    //定金付款成功--房东
			if($sendtype=="DJ001"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		     //定金申请退款--租客
			if($sendtype=="DJ002"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		     //定金申请退款--客服
			if($sendtype=="DJ003"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		      //保证金
			if($sendtype=="BZJ001"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		    if($sendtype=="BZJ002"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		    if($sendtype=="EZA008"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		    if($sendtype=="FHS005"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }
		    if($sendtype=="FHS009" || $sendtype=="FHS011"){
				$sendArr['phonenumber']=$ordersArr['renter_phone'];
				$sendArr['smstype']=$sendtype;
				$sendArr['timestamp']=$ordersArr['create_time'];
				$sendArr['name']=$ordersArr['renter_name'];
				if($sendtype=="FHS011"){
					$sendArr['name']='400-8786-999转8005';
				}
				$sendArr['money']=$ordersArr['price_cnt'];
				$sendArr['orderid']=$ordersArr['id'];
				sendPhoneContent($sendArr);
		    }

	}
		
}

?>